name: CI Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  preparation:
    runs-on: ubuntu-latest
    outputs:
      runId: ${{ steps.prepare.outputs.runId }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Preparation
        id: prepare
        run: |
          runId=$(date +%s)
          echo "runId=$runId" >> $GITHUB_OUTPUT

  jobA:
    runs-on: ubuntu-latest
    needs: preparation
    steps:
      - name: Run JobA
        run: |
          echo "Running JobA with runId=${{ needs.preparation.outputs.runId }}"

  jobB:
    runs-on: ubuntu-latest
    needs: preparation
    steps:
      - name: Run JobB
        run: |
          echo "Running JobB with runId=${{ needs.preparation.outputs.runId }}"

  jobC:
    runs-on: ubuntu-latest
    needs: preparation
    steps:
      - name: Run JobC
        run: |
          echo "Running JobC with runId=${{ needs.preparation.outputs.runId }}"

  integration:
    # runs-on: ubuntu-latest
    needs: [jobA, jobB, jobC]
    steps:
      - name: Integration
        run: |
          echo "Integrating results from JobA, JobB, JobC"

  deploy:
    runs-on: ubuntu-latest
    needs: integration
    steps:
      - name: Deploy
        run: |
          echo "Deploying..."

